//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BirthdayCake.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGuest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblGuest()
        {
            this.tblOrders = new HashSet<tblOrder>();
        }
    
        public int GuestID { get; set; }
        public string GuestNameSurname { get; set; }
        public string GuestAddress { get; set; }
        public string PhoneNumber { get; set; }
        public string GuestUsername { get; set; }
        public string GuestPassword { get; set; }
        public Nullable<int> NumberOrder { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrder> tblOrders { get; set; }
    }
}
